### ISSUE TITLE
readme中@hb/vue2vite不存在

### ISSUE THREAD

**Issue by zxx960** [caoxiemeihao/vite-plugin-vue2-compatible#1]
readme中@hb/vue2vite不存在

**Comment by caoxiemeihao** [comment]
`@hb/vue2vite` 是内网包
这个项目已经废弃
参考链接 https://juejin.cn/post/7012880929102233637

**Comment by zxx960** [comment]
> `@hb/vue2vite` 是内网包 这个项目已经废弃 参考链接 https://juejin.cn/post/7012880929102233637

谢谢！
