### ISSUE TITLE
jsx语法报错

### ISSUE THREAD

**Issue by chengfengfengwang** [caoxiemeihao/vite-plugin-vue2-compatible#2]
vite.config.js配置如下

import { defineConfig } from 'vite'
import { createVuePlugin } from 'vite-plugin-vue2'
import { renderJsx } from 'vite-plugin-vue2-compatible'
const path = require('path');

export default defineConfig({
  plugins: [
    createVuePlugin({
      jsx: true,
      jsxOptions: {
        presets: ['@vue/babel-preset-jsx']
      }
    },
    renderJsx()
  )],
  server: {
    port: 5000,
    host: '0.0.0.0',
    hot: true,
    // https: true,
    overlay: true,
    openPage: '/login',
    // new proxy tables as same as the past 'proxyTable'
    proxy: {
      '/api': {
        target: 'https://dss-pre.xiongmaopeilian.com/',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, '')
        // pathRewrite: {
        //   '^/api': ''
        // }
      },
      '/op': {
        target: 'http://op-dev.xiaoyezi.com/',
        changeOrigin: true,
        pathRewrite: {
          '^/op': ''
        }
      }
    }
  },
  resolve: {
    alias: [
      {
        find: '@',
        replacement: path.resolve(__dirname, 'src')
      }
    ],
    extensions: ['.vue', '.mjs', '.js', '.ts', '.jsx', '.tsx', '.json']
  },
})

报错信息如下：
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
/Users/xiaoyezi/code/dss/src/views/communityWorkbench/components/origin_course_students_tab.vue:219:28
217|                      onInput={(e, a) => this.handleRemarkInput(e, row)}
218|                      placeholder="请输入内容"
219|                    ></Input>
   |                             ^
220|                    <el-button
221|                      class="wechat-input-ok"
    at formatError (/Users/xiaoyezi/code/dss/node_modules/vite/dist/node/chunks/dep-fcec4469.js:42631:46)
    at TransformContext.error (/Users/xiaoyezi/code/dss/node_modules/vite/dist/node/chunks/dep-fcec4469.js:42627:19)
    at TransformContext.transform (/Users/xiaoyezi/code/dss/node_modules/vite/dist/node/chunks/dep-fcec4469.js:81321:22)
    at async Object.transform (/Users/xiaoyezi/code/dss/node_modules/vite/dist/node/chunks/dep-fcec4469.js:42847:30)
    at async doTransform (/Users/xiaoyezi/code/dss/node_modules/vite/dist/node/chunks/dep-fcec4469.js:5

**Comment by caoxiemeihao** [comment]
安装 [vite-plugin-lang-jsx](https://www.npmjs.com/package/vite-plugin-lang-jsx)
